# Generated by Django 3.0 on 2023-04-25 18:15

from django.db import migrations


def move_profiles(apps, schema_editor):
    OldProfile = apps.get_model('oc_lettings_site', 'Profile')
    NewProfile = apps.get_model('profiles', 'Profile')

    objs = list()


    for old_object in OldProfile.objects.all():
        favorite_city = old_object.favorite_city
        user_id = old_object.user_id

        new_profile = NewProfile(favorite_city=favorite_city, user_id=user_id)
        objs.append(new_profile)

    NewProfile.objects.bulk_create(objs)


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(move_profiles, migrations.RunPython.noop)
    ]
