# Generated by Django 3.0 on 2023-04-26 08:23

from django.db import migrations


def move_profiles(apps, schema_editor):
    OldProfile = apps.get_model('oc_lettings_site', 'Profile')
    NewProfile = apps.get_model('profiles', 'Profile')

    objs = list()

    for old_object in OldProfile.objects.all():
        favorite_city = old_object.favorite_city
        old_user = old_object.user

        new_profile = NewProfile(favorite_city=favorite_city, user=old_user)
        objs.append(new_profile)

    NewProfile.objects.bulk_create(objs)

class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('oc_lettings_site', '0003_auto_20230426_1023')
    ]

    operations = [
        migrations.RunPython(move_profiles, migrations.RunPython.noop)
    ]
